# Workflow to run CI and Tests

name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
  
  jobs:
    ci:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [14.x, 16.x]
      steps:
        - name: Checkout repo
          uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install dependencies
          run: npm ci

        - name: Test & lint
          run: npm run test